#  1.eureka.client.serviceUrl.defaultZone配置项的地址，不能使用localhost，要使用域名，DNS解析请自行配置。
#  2.spring.application.name要一致（这个个人测试默认不配也可以）

#服务名和服务暴露的接口
server:
  port: 6400
# 设置spring应用命名，可以自定义，非必要
spring:
  application:
    name: redis-server01
  redis:
    port: 6379
    host: 127.0.0.1
    password: 123456q
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
    timeout: 0

eureka:
  instance:
    # 设置eureka实例名称，建议与配置文件的变量相同，必须和Linux系统域名相同,本机演示，不同的注册中心需要有不同的实例名
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://localhost:9001/eureka/,http://localhost1:9002/eureka/

