# 端口上下文
server:
  port: 9111
  servlet:
    context-path: /aub
spring:
  application:
    name: service-user
  # redis配置
  redis:
    port: 6379
    host: 127.0.0.1
    password: 123456q
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
    timeout: 0

# 服务注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/,http://localhost1:9002/eureka/
