# 端口上下文
server:
  port: 9111
  servlet:
    context-path: /aub
  tomcat:
    basedir: /tmp
    accesslog:
      enabled: true
spring:
  application:
    name: service-user
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_user?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
  # redis配置
  #本地root启动redis
  redis:
    port: 6379
    host: 127.0.0.1
    password: 123456q
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
    timeout: 4000

# mybatis
mybatis:
  #design.first.config_client.config-location: classpath:design.first.config_client.config/mybatis-design.first.config_client.config.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: design.parent.overall.entity
  # sql打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰
    map-underscore-to-camel-case: true

#shiro密码权限验证
#shiro:
#  filterChainDefinitionMap:
#    /logout: logout
#    /**: authc
#    /index2: anon
session:
  redis:
    # 会话保存时间/秒
    expireTime: 36000


# 服务注册
eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: false
    # 实例的主机名
    hostname: localhost
    appname: ${spring.application.name}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    server:
      enable-self-preservation: false
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/,http://localhost1:9002/eureka/

