server:
  port: 9111
  servlet:
    context-path: /aub
spring:
  application:
    name: service-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/,http://localhost1:9002/eureka/
